on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      PYTHON_VERSION: 3.8

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/yvondir-ateldil
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rg.fr-par.scw.cloud/yvondir-ateldil/yvondir-ateldil-bot:latest
          build-args: |
            PYTHON_VERSION=${{ PYTHON_VERSION }}
